### ISSUE TITLE
Pequenas correções na documentação

### ISSUE THREAD

**Issue by joaocaram** [ICEI-PUCMinas-PSG-SI-TI/tiaw_2023-1-gasolinabarata#8]
@ICEI-PUCMinas-PSG-SI-TI/gasolinabarata  , atenção: 
**_Corrigir:_**

- no modelo havia como colocar as figuras dentro do relatório, não links para as imagens. Façam isso, por favor, tanto para as personas como para os wireframes.
- persona 2 e persona 3 estão a mesma (Gustavo Rezende)

**Comment by VictorViniciosVieira** [comment]
Corrigido
